# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20170618_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_content',
            new_name='table_of_content',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_chapter',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_number',
            new_name='number',
        ),
    ]
